services:
  mysql_DB:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data_user:/var/lib/mysql
    ports:
      - '${DOCKER_DB_PORT}:3306'
    networks:
      - service_network

  user_service:
    container_name: user_service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '${DOCKER_SERVICE_PORT}:5000'
    networks:
      - service_network
    depends_on:
      - mysql_DB

volumes:
  db_data_user:

networks:
  service_network:
    name: service_network

